const SuccessStatus = {
  SUCCESS_CONNECT: 'SUCCESS_CONNECT',
  SUCCESS_TRAIN: 'SUCCESS_TRAIN',
  SUCCESS_GET: 'SUCCESS_GET',
  SUCCESS_CREATE: 'SUCCESS_CREATE',
  SUCCESS_DELETE: 'SUCCESS_DELETE',
};

export default SuccessStatus